// India district list (749) — source: India Post pincode dataset (Book1.xlsx).
// Powers the search autocomplete so a user can type e.g. "luc" -> "Lucknow".
// Regenerate from the spreadsheet, do not hand-edit.

export const DISTRICTS: readonly string[] = [
  "24 Paraganas North",
  "24 Paraganas South",
  "Adilabad",
  "Agar Malwa",
  "Agra",
  "Ahmadabad",
  "Ahmednagar",
  "Aizawl",
  "Ajmer",
  "Akola",
  "Alappuzha",
  "Aligarh",
  "Alipurduar",
  "Alirajpur",
  "Alluri Sitharama Raju",
  "Almora",
  "Alwar",
  "Ambala",
  "Ambedkar Nagar",
  "Amethi",
  "Amravati",
  "Amreli",
  "Amritsar",
  "Amroha",
  "Anakapalli",
  "Anand",
  "Anantapur",
  "Anantnag",
  "Anjaw",
  "Annamayya",
  "Anugul",
  "Anuppur",
  "Araria",
  "Ariyalur",
  "Arvalli",
  "Arwal",
  "Ashoknagar",
  "Auraiya",
  "Aurangabad",
  "Ayodhya",
  "Azamgarh",
  "Bagalkot",
  "Bageshwar",
  "Baghpat",
  "Bahraich",
  "Bajali",
  "Baksa",
  "Balaghat",
  "Balangir",
  "Baleshwar",
  "Ballari",
  "Ballia",
  "Balod",
  "Baloda Bazar",
  "Balrampur",
  "Banas Kantha",
  "Banda",
  "Bandipora",
  "Banka",
  "Bankura",
  "Banswara",
  "Bapatla",
  "Barabanki",
  "Baramulla",
  "Baran",
  "Bareilly",
  "Bargarh",
  "Barmer",
  "Barnala",
  "Barpeta",
  "Barwani",
  "Bastar",
  "Basti",
  "Bathinda",
  "Beed",
  "Begusarai",
  "Belagavi",
  "Bemetara",
  "Bengaluru Rural",
  "Bengaluru Urban",
  "Betul",
  "Bhadohi",
  "Bhadradri Kothagudem",
  "Bhadrak",
  "Bhagalpur",
  "Bhandara",
  "Bharatpur",
  "Bharuch",
  "Bhavnagar",
  "Bhilwara",
  "Bhind",
  "Bhiwani",
  "Bhojpur",
  "Bhopal",
  "Bidar",
  "Bijapur",
  "Bijnor",
  "Bikaner",
  "Bilaspur",
  "Birbhum",
  "Bishnupur",
  "Biswanath",
  "Bokaro",
  "Bongaigaon",
  "Botad",
  "Boudh",
  "Budaun",
  "Budgam",
  "Bulandshahr",
  "Buldhana",
  "Bundi",
  "Burhanpur",
  "Buxar",
  "Cachar",
  "Central",
  "Chamarajanagara",
  "Chamba",
  "Chamoli",
  "Champawat",
  "Champhai",
  "Chandauli",
  "Chandel",
  "Chandigarh",
  "Chandrapur",
  "Changlang",
  "Charaideo",
  "Charki Dadri",
  "Chatra",
  "Chengalpattu",
  "Chennai",
  "Chhatarpur",
  "Chhindwara",
  "Chhotaudepur",
  "Chikkaballapura",
  "Chikkamagaluru",
  "Chirang",
  "Chitradurga",
  "Chitrakoot",
  "Chittoor",
  "Chittorgarh",
  "Churachandpur",
  "Churu",
  "Coimbatore",
  "Coochbehar",
  "Cuddalore",
  "Cuttack",
  "Dadra and Nagar Haveli",
  "Dakshina Kannada",
  "Daman",
  "Damoh",
  "Dang",
  "Dantewada",
  "Darbhanga",
  "Darjeeling",
  "Darrang",
  "Datia",
  "Dausa",
  "Davangere",
  "Dehradun",
  "Deogarh",
  "Deoghar",
  "Deoria",
  "Devbhumi Dwarka",
  "Dewas",
  "Dhalai",
  "Dhamtari",
  "Dhanbad",
  "Dhar",
  "Dharmapuri",
  "Dharwad",
  "Dhemaji",
  "Dhenkanal",
  "Dholpur",
  "Dhubri",
  "Dhule",
  "Dibang Valley",
  "Dibrugarh",
  "Dima Hasao",
  "Dimapur",
  "Dinajpur Dakshin",
  "Dinajpur Uttar",
  "Dindigul",
  "Dindori",
  "Diu",
  "Doda",
  "Dohad",
  "Dumka",
  "Dungarpur",
  "Durg",
  "East",
  "East District",
  "East Garo Hills",
  "East Godavari",
  "East Jaintia Hills",
  "East Kameng",
  "East Khasi Hills",
  "East Nimar",
  "East Siang",
  "East Singhbum",
  "Eluru",
  "Ernakulam",
  "Erode",
  "Etah",
  "Etawah",
  "Faridabad",
  "Faridkot",
  "Farrukhabad",
  "Fatehabad",
  "Fatehgarh Sahib",
  "Fatehpur",
  "Fazilka",
  "Firozabad",
  "Firozepur",
  "Gadag",
  "Gadchiroli",
  "Gajapati",
  "Ganderbal",
  "Gandhinagar",
  "Ganganagar",
  "Ganjam",
  "Garhwa",
  "Gariyaband",
  "Gaurella Pendra Marwahi",
  "Gautam Buddha Nagar",
  "Gaya",
  "Ghaziabad",
  "Ghazipur",
  "Gir Somnath",
  "Giridih",
  "Goalpara",
  "Godda",
  "Golaghat",
  "Gomati",
  "Gonda",
  "Gondia",
  "Gopalganj",
  "Gorakhpur",
  "Gumla",
  "Guna",
  "Guntur",
  "Gurdaspur",
  "Gurugram",
  "Gwalior",
  "Hailakandi",
  "Hamirpur",
  "Hanumakonda",
  "Hanumangarh",
  "Hapur",
  "Harda",
  "Hardoi",
  "Haridwar",
  "Hassan",
  "Hathras",
  "Haveri",
  "Hazaribagh",
  "Hingoli",
  "Hisar",
  "Hnahthial",
  "Hojai",
  "Hooghly",
  "Hoshangabad",
  "Hoshiarpur",
  "Howrah",
  "Hyderabad",
  "Idukki",
  "Imphal East",
  "Imphal West",
  "Indore",
  "Jabalpur",
  "Jagatsinghapur",
  "Jagitial",
  "Jaipur",
  "Jaisalmer",
  "Jajapur",
  "Jalandhar",
  "Jalaun",
  "Jalgaon",
  "Jalna",
  "Jalore",
  "Jalpaiguri",
  "Jammu",
  "Jamnagar",
  "Jamtara",
  "Jamui",
  "Jangoan",
  "Janjgir-champa",
  "Jashpur",
  "Jaunpur",
  "Jayashankar Bhupalapally",
  "Jehanabad",
  "Jhabua",
  "Jhajjar",
  "Jhalawar",
  "Jhansi",
  "Jhargram",
  "Jharsuguda",
  "Jhunjhunu",
  "Jind",
  "Jiribam",
  "Jodhpur",
  "Jogulamba Gadwal",
  "Jorhat",
  "Junagadh",
  "Kabirdham",
  "Kachchh",
  "Kaimur (bhabua)",
  "Kaithal",
  "Kakching",
  "Kakinada",
  "Kalaburagi",
  "Kalahandi",
  "Kalimpong",
  "Kallakurichi",
  "Kamareddy",
  "Kamjong",
  "Kamle",
  "Kamrup",
  "Kamrup Metro",
  "Kanchipuram",
  "Kandhamal",
  "Kangpokpi",
  "Kangra",
  "Kanker",
  "Kannauj",
  "Kanniyakumari",
  "Kannur",
  "Kanpur Dehat",
  "Kanpur Nagar",
  "Kapurthala",
  "Karaikal",
  "Karauli",
  "Karbi Anglong",
  "Kargil",
  "Karimganj",
  "Karimnagar",
  "Karnal",
  "Karur",
  "Kasaragod",
  "Kasganj",
  "Kathua",
  "Katihar",
  "Katni",
  "Kaushambi",
  "Kendrapara",
  "Kendujhar",
  "Khagaria",
  "Khammam",
  "Khargone",
  "Khawzawl",
  "Kheda",
  "Kheri",
  "Khordha",
  "Khowai",
  "Khunti",
  "Kinnaur",
  "Kiphire",
  "Kishanganj",
  "Kishtwar",
  "Kodagu",
  "Koderma",
  "Kohima",
  "Kokrajhar",
  "Kolar",
  "Kolasib",
  "Kolhapur",
  "Kolkata",
  "Kollam",
  "Konaseema",
  "Kondagaon",
  "Koppal",
  "Koraput",
  "Korba",
  "Korea",
  "Kota",
  "Kottayam",
  "Kozhikode",
  "Kra Daadi",
  "Krishna",
  "Krishnagiri",
  "Kulgam",
  "Kullu",
  "Kumuram Bheem Asifabad",
  "Kupwara",
  "Kurnool",
  "Kurukshetra",
  "Kurung Kumey",
  "Kushi Nagar",
  "Lahul and Spiti",
  "Lakhimpur",
  "Lakhisarai",
  "Lakshadweep District",
  "Lalitpur",
  "Latehar",
  "Latur",
  "Lawngtlai",
  "Leh Ladakh",
  "Leparada",
  "Lohardaga",
  "Lohit",
  "Longding",
  "Longleng",
  "Lower Dibang Valley",
  "Lower Siang",
  "Lower Subansiri",
  "Lucknow",
  "Ludhiana",
  "Lunglei",
  "Madhepura",
  "Madhubani",
  "Madurai",
  "Mahabubabad",
  "Mahabubnagar",
  "Maharajganj",
  "Mahasamund",
  "Mahe",
  "Mahendragarh",
  "Mahesana",
  "Mahisagar",
  "Mahoba",
  "Mainpuri",
  "Majuli",
  "Malappuram",
  "Maldah",
  "Malerkotla",
  "Malkangiri",
  "Mamit",
  "Mancherial",
  "Mandi",
  "Mandla",
  "Mandsaur",
  "Mandya",
  "Mansa",
  "Marigaon",
  "Mathura",
  "Mau",
  "Mayiladuthurai",
  "Mayurbhanj",
  "Medak",
  "Medchal Malkajgiri",
  "Medinipur East",
  "Medinipur West",
  "Meerut",
  "Mirzapur",
  "Moga",
  "Mokokchung",
  "Mon",
  "Moradabad",
  "Morbi",
  "Morena",
  "Mulugu",
  "Mumbai",
  "Mumbai Suburban",
  "Mungeli",
  "Munger",
  "Murshidabad",
  "Muzaffarnagar",
  "Muzaffarpur",
  "Mysuru",
  "Nabarangpur",
  "Nadia",
  "Nagaon",
  "Nagapattinam",
  "Nagarkurnool",
  "Nagaur",
  "Nagpur",
  "Nainital",
  "Nalanda",
  "Nalbari",
  "Nalgonda",
  "Namakkal",
  "Namsai",
  "Nanded",
  "Nandurbar",
  "Nandyal",
  "Narayanpet",
  "Narayanpur",
  "Narmada",
  "Narsinghpur",
  "Nashik",
  "Navsari",
  "Nawada",
  "Nayagarh",
  "Neemuch",
  "New Delhi",
  "Nicobars",
  "Nirmal",
  "Niwari",
  "Nizamabad",
  "Noklak",
  "Noney",
  "North",
  "North and Middle Andaman",
  "North District",
  "North East",
  "North Garo Hills",
  "North Goa",
  "North Tripura",
  "North West",
  "Ntr",
  "Nuapada",
  "Nuh",
  "Osmanabad",
  "Pakke Kessang",
  "Pakur",
  "Pakyong",
  "Palakkad",
  "Palamu",
  "Palghar",
  "Pali",
  "Palnadu",
  "Palwal",
  "Panch Mahals",
  "Panchkula",
  "Panipat",
  "Panna",
  "Papum Pare",
  "Parbhani",
  "Parvathipuram Manyam",
  "Paschim Bardhaman",
  "Pashchim Champaran",
  "Patan",
  "Pathanamthitta",
  "Pathankot",
  "Patiala",
  "Patna",
  "Pauri Garhwal",
  "Peddapalli",
  "Perambalur",
  "Peren",
  "Phek",
  "Pherzawl",
  "Pilibhit",
  "Pithoragarh",
  "Pondicherry",
  "Poonch",
  "Porbandar",
  "Prakasam",
  "Pratapgarh",
  "Prayagraj",
  "Pudukkottai",
  "Pulwama",
  "Pune",
  "Purba Bardhaman",
  "Purbi Champaran",
  "Puri",
  "Purnia",
  "Purulia",
  "Rae Bareli",
  "Raichur",
  "Raigad",
  "Raigarh",
  "Raipur",
  "Raisen",
  "Rajanna Sircilla",
  "Rajgarh",
  "Rajkot",
  "Rajnandgaon",
  "Rajouri",
  "Rajsamand",
  "Ramanagara",
  "Ramanathapuram",
  "Ramban",
  "Ramgarh",
  "Rampur",
  "Ranchi",
  "Ranga Reddy",
  "Ranipet",
  "Ratlam",
  "Ratnagiri",
  "Rayagada",
  "Reasi",
  "Rewa",
  "Rewari",
  "Ri Bhoi",
  "Rohtak",
  "Rohtas",
  "Rudra Prayag",
  "Rupnagar",
  "S.a.s Nagar",
  "Sabar Kantha",
  "Sagar",
  "Saharanpur",
  "Saharsa",
  "Sahebganj",
  "Saiha",
  "Saitual",
  "Salem",
  "Samastipur",
  "Samba",
  "Sambalpur",
  "Sambhal",
  "Sangareddy",
  "Sangli",
  "Sangrur",
  "Sant Kabeer Nagar",
  "Saraikela Kharsawan",
  "Saran",
  "Satara",
  "Satna",
  "Sawai Madhopur",
  "Sehore",
  "Senapati",
  "Seoni",
  "Sepahijala",
  "Serchhip",
  "Shahdara",
  "Shahdol",
  "Shahid Bhagat Singh Nagar",
  "Shahjahanpur",
  "Shajapur",
  "Shamli",
  "Sheikhpura",
  "Sheohar",
  "Sheopur",
  "Shi Yomi",
  "Shimla",
  "Shivamogga",
  "Shivpuri",
  "Shopian",
  "Shravasti",
  "Siang",
  "Siddharth Nagar",
  "Siddipet",
  "Sidhi",
  "Sikar",
  "Simdega",
  "Sindhudurg",
  "Singrauli",
  "Sirmaur",
  "Sirohi",
  "Sirsa",
  "Sitamarhi",
  "Sitapur",
  "Sivaganga",
  "Sivasagar",
  "Siwan",
  "Solan",
  "Solapur",
  "Sonbhadra",
  "Sonepur",
  "Sonipat",
  "Sonitpur",
  "Soreng",
  "South",
  "South Andamans",
  "South District",
  "South East",
  "South Garo Hills",
  "South Goa",
  "South Salmara Mancachar",
  "South Tripura",
  "South West",
  "South West Garo Hills",
  "South West Khasi Hills",
  "Spsr Nellore",
  "Sri Muktsar Sahib",
  "Sri Sathya Sai",
  "Srikakulam",
  "Srinagar",
  "Sukma",
  "Sultanpur",
  "Sundargarh",
  "Supaul",
  "Surajpur",
  "Surat",
  "Surendranagar",
  "Surguja",
  "Suryapet",
  "Tamenglong",
  "Tapi",
  "Tarn Taran",
  "Tawang",
  "Tehri Garhwal",
  "Tengnoupal",
  "Tenkasi",
  "Thane",
  "Thanjavur",
  "The Nilgiris",
  "Theni",
  "Thiruvallur",
  "Thiruvananthapuram",
  "Thiruvarur",
  "Thoubal",
  "Thrissur",
  "Tikamgarh",
  "Tinsukia",
  "Tirap",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupathur",
  "Tirupati",
  "Tiruppur",
  "Tiruvannamalai",
  "Tonk",
  "Tuensang",
  "Tumakuru",
  "Tuticorin",
  "Udaipur",
  "Udalguri",
  "Udam Singh Nagar",
  "Udhampur",
  "Udupi",
  "Ujjain",
  "Ukhrul",
  "Umaria",
  "Una",
  "Unakoti",
  "Unnao",
  "Upper Siang",
  "Upper Subansiri",
  "Uttar Kashi",
  "Uttara Kannada",
  "Vadodara",
  "Vaishali",
  "Valsad",
  "Varanasi",
  "Vellore",
  "Vidisha",
  "Vijayapura",
  "Vijaynagar",
  "Vikarabad",
  "Villupuram",
  "Virudhunagar",
  "Visakhapatanam",
  "Vizianagaram",
  "Wanaparthy",
  "Warangal",
  "Wardha",
  "Washim",
  "Wayanad",
  "West",
  "West District",
  "West Garo Hills",
  "West Godavari",
  "West Jaintia Hills",
  "West Kameng",
  "West Karbi Anglong",
  "West Khasi Hills",
  "West Siang",
  "West Singhbhum",
  "West Tripura",
  "Wokha",
  "Y.s.r.",
  "Yadadri Bhuvanagiri",
  "Yadgir",
  "Yamunanagar",
  "Yanam",
  "Yavatmal",
  "Zunheboto",
];
