// District name (lowercase) -> nearest railway station code + nearest airport
// IATA. Station code is the district's own station where the name matches the
// IR station registry (list_of_stations.json), otherwise the nearest major
// railhead by great-circle distance from the district centroid. Airport is the
// nearest scheduled airport (list-of-airports-in-india.csv). Used as a fallback
// in toStationCode() / toIata() so a search for any district still resolves.
// Regenerate with scratchpad/gen-district-hubs.mjs — do not hand-edit.
//   airport cap 450 km · nearest-railhead cap 275 km

export interface DistrictHub {
  station?: string;
  iata?: string;
}

export const DISTRICT_HUBS: Record<string, DistrictHub> = {
  "24 paraganas north": {"station":"BT","iata":"CCU"},
  "24 paraganas south": {"station":"BRP","iata":"CCU"},
  "adilabad": {"station":"ADB","iata":"NDC"},
  "agar malwa": {"station":"BPL","iata":"BHO"},
  "agra": {"station":"AGA","iata":"GWL"},
  "ahmadabad": {"station":"ADI","iata":"AMD"},
  "ahmednagar": {"station":"AWB","iata":"SAG"},
  "aizawl": {"iata":"AJL"},
  "ajmer": {"station":"AII","iata":"KQH"},
  "akola": {"station":"AK","iata":"NDC"},
  "alappuzha": {"station":"ERS","iata":"COK"},
  "aligarh": {"station":"ALJN","iata":"GWL"},
  "alipurduar": {"station":"GHY","iata":"IXB"},
  "alirajpur": {"station":"BRC","iata":"BDQ"},
  "alluri sitharama raju": {"station":"VSKP","iata":"RJA"},
  "almora": {"station":"HW","iata":"DED"},
  "alwar": {"station":"AWR","iata":"JAI"},
  "ambala": {"station":"UBC","iata":"IXC"},
  "ambedkar nagar": {"station":"GKP","iata":"GOP"},
  "amethi": {"station":"AME","iata":"LKO"},
  "amravati": {"station":"AMI","iata":"NAG"},
  "amreli": {"station":"AE","iata":"DIU"},
  "amritsar": {"station":"ASR","iata":"ATQ"},
  "amroha": {"station":"AMRO","iata":"DEL"},
  "anakapalli": {"station":"VSKP","iata":"VTZ"},
  "anand": {"station":"ANND","iata":"BDQ"},
  "anantapur": {"station":"ATP","iata":"CDP"},
  "anantnag": {"station":"ANT","iata":"SXR"},
  "anjaw": {"iata":"DIB"},
  "annamayya": {"station":"TPTY","iata":"CDP"},
  "anugul": {"station":"BBS","iata":"BBI"},
  "anuppur": {"station":"APR","iata":"JLR"},
  "araria": {"station":"PNBE","iata":"IXB"},
  "ariyalur": {"station":"ALU","iata":"TRZ"},
  "arvalli": {"station":"ADI","iata":"AMD"},
  "arwal": {"station":"BSB","iata":"GAY"},
  "ashoknagar": {"station":"VGLJ","iata":"BHO"},
  "auraiya": {"station":"CNB","iata":"GWL"},
  "aurangabad": {"station":"AWB","iata":"IXU"},
  "ayodhya": {"station":"AY","iata":"LKO"},
  "azamgarh": {"station":"NGP","iata":"NAG"},
  "bagalkot": {"station":"BGK","iata":"HBX"},
  "bageshwar": {"station":"HW","iata":"DED"},
  "baghpat": {"station":"NDLS","iata":"DEL"},
  "bahraich": {"station":"BRK","iata":"LKO"},
  "bajali": {"station":"GHY","iata":"GAU"},
  "baksa": {"station":"GHY","iata":"GAU"},
  "balaghat": {"station":"BTC","iata":"NAG"},
  "balangir": {"station":"BLGR","iata":"RPR"},
  "baleshwar": {"station":"BBS","iata":"BBI"},
  "ballari": {"station":"SBC","iata":"HBX"},
  "ballia": {"station":"BUI","iata":"PAT"},
  "balod": {"station":"BXA","iata":"RPR"},
  "baloda bazar": {"station":"R","iata":"RPR"},
  "balrampur": {"station":"BLP","iata":"VNS"},
  "banas kantha": {"station":"ADI","iata":"AMD"},
  "banda": {"station":"BNDA","iata":"HJR"},
  "bandipora": {"station":"JAT","iata":"SXR"},
  "banka": {"station":"BAKA","iata":"GAY"},
  "bankura": {"station":"BQA","iata":"RDP"},
  "banswara": {"station":"UDZ","iata":"UDR"},
  "bapatla": {"station":"BPP","iata":"VGA"},
  "barabanki": {"station":"LKO","iata":"LKO"},
  "baramulla": {"station":"BRML","iata":"SXR"},
  "baran": {"station":"BAZ","iata":"BHO"},
  "bareilly": {"station":"BC","iata":"DED"},
  "bargarh": {"station":"BRG","iata":"RPR"},
  "barmer": {"station":"BME","iata":"JDH"},
  "barnala": {"station":"BNN","iata":"IXC"},
  "barpeta": {"station":"GHY","iata":"GAU"},
  "barwani": {"station":"INDB","iata":"IDR"},
  "bastar": {"station":"VSKP","iata":"VTZ"},
  "basti": {"station":"BST","iata":"GOP"},
  "bathinda": {"station":"LDH","iata":"AIP"},
  "beed": {"station":"AWB","iata":"LTU"},
  "begusarai": {"station":"PNBE","iata":"PAT"},
  "belagavi": {"station":"MAO","iata":"IXG"},
  "bemetara": {"station":"R","iata":"RPR"},
  "bengaluru rural": {"station":"SBC","iata":"BLR"},
  "bengaluru urban": {"station":"SBC","iata":"BLR"},
  "betul": {"station":"BZU","iata":"BHO"},
  "bhadohi": {"station":"BOY","iata":"VNS"},
  "bhadradri kothagudem": {"station":"BZA","iata":"VGA"},
  "bhadrak": {"station":"BBS","iata":"BBI"},
  "bhagalpur": {"station":"BGP","iata":"PAT"},
  "bhandara": {"station":"NGP","iata":"NAG"},
  "bharatpur": {"station":"BRTP","iata":"GWL"},
  "bharuch": {"station":"BH","iata":"BDQ"},
  "bhavnagar": {"station":"ST","iata":"BHU"},
  "bhilwara": {"station":"BHL","iata":"UDR"},
  "bhind": {"station":"BIX","iata":"GWL"},
  "bhiwani": {"station":"BNW","iata":"DEL"},
  "bhojpur": {"station":"PNBE","iata":"PAT"},
  "bhopal": {"station":"BPL","iata":"BHO"},
  "bidar": {"station":"BIDR","iata":"HYD"},
  "bijapur": {"station":"BJP","iata":"RJA"},
  "bijnor": {"station":"BJO","iata":"GWL"},
  "bikaner": {"station":"BKN","iata":"JDH"},
  "bilaspur": {"station":"BSP","iata":"GWL"},
  "birbhum": {"station":"HWH","iata":"RDP"},
  "bishnupur": {"station":"VSU","iata":"IMF"},
  "biswanath": {"station":"GHY","iata":"TEZ"},
  "bokaro": {"station":"RNC","iata":"IXR"},
  "bongaigaon": {"station":"BGGN","iata":"GAU"},
  "botad": {"station":"BTD","iata":"BHU"},
  "boudh": {"station":"BBS","iata":"BBI"},
  "budaun": {"station":"BEM","iata":"DEL"},
  "budgam": {"station":"BDGM","iata":"SXR"},
  "bulandshahr": {"station":"BSC","iata":"DEL"},
  "buldhana": {"station":"AWB","iata":"IXU"},
  "bundi": {"station":"BUDI","iata":"JAI"},
  "burhanpur": {"station":"BAU","iata":"IDR"},
  "buxar": {"station":"BXR","iata":"PAT"},
  "cachar": {"station":"GHY","iata":"IXS"},
  "central": {"station":"NDLS","iata":"DEL"},
  "chamarajanagara": {"station":"MYS","iata":"CJB"},
  "chamba": {"station":"JAT","iata":"IXP"},
  "chamoli": {"station":"HW","iata":"DED"},
  "champawat": {"station":"HW","iata":"DED"},
  "champhai": {"iata":"AJL"},
  "chandauli": {"station":"BSB","iata":"VNS"},
  "chandel": {"iata":"IMF"},
  "chandigarh": {"station":"CDG","iata":"IXC"},
  "chandrapur": {"station":"CD","iata":"NAG"},
  "changlang": {"iata":"DIB"},
  "charaideo": {"station":"GHY","iata":"DMU"},
  "charki dadri": {"station":"NDLS","iata":"DEL"},
  "chatra": {"station":"CTR","iata":"GAY"},
  "chengalpattu": {"station":"CGL","iata":"MAA"},
  "chennai": {"station":"MAS","iata":"MAA"},
  "chhatarpur": {"station":"VGLJ","iata":"HJR"},
  "chhindwara": {"station":"CWA","iata":"NAG"},
  "chhotaudepur": {"station":"PUNE","iata":"KLH"},
  "chikkaballapura": {"station":"SBC","iata":"BLR"},
  "chikkamagaluru": {"station":"MAQ","iata":"IXE"},
  "chirang": {"station":"GHY","iata":"GAU"},
  "chitradurga": {"station":"SBC","iata":"BLR"},
  "chitrakoot": {"station":"PRYJ","iata":"TNI"},
  "chittoor": {"station":"CTO","iata":"TIR"},
  "chittorgarh": {"station":"UDZ","iata":"UDR"},
  "churachandpur": {"station":"GHY","iata":"IMF"},
  "churu": {"station":"CUR","iata":"JAI"},
  "coimbatore": {"station":"CBE","iata":"CJB"},
  "coochbehar": {"station":"GHY","iata":"IXB"},
  "cuddalore": {"station":"MAS","iata":"TRZ"},
  "cuttack": {"station":"CTC","iata":"BBI"},
  "dadra and nagar haveli": {"station":"NK","iata":"ISK"},
  "dakshina kannada": {"station":"MAQ","iata":"IXE"},
  "daman": {"station":"ST","iata":"STV"},
  "damoh": {"station":"DMO","iata":"JLR"},
  "dang": {"station":"NK","iata":"ISK"},
  "dantewada": {"station":"VSKP","iata":"RJA"},
  "darbhanga": {"station":"DBG","iata":"GAY"},
  "darjeeling": {"station":"DJ","iata":"IXB"},
  "darrang": {"station":"GHY","iata":"GAU"},
  "datia": {"station":"DAA","iata":"GWL"},
  "dausa": {"station":"DO","iata":"JAI"},
  "davangere": {"station":"DVG","iata":"HBX"},
  "dehradun": {"station":"DDN","iata":"DED"},
  "deogarh": {"station":"BBS","iata":"BBI"},
  "deoghar": {"station":"DGHR","iata":"RDP"},
  "deoria": {"station":"GKP","iata":"GOP"},
  "devbhumi dwarka": {"station":"RJT","iata":"PBD"},
  "dewas": {"station":"DWX","iata":"BHO"},
  "dhalai": {"station":"GHY","iata":"AJL"},
  "dhamtari": {"station":"DTR","iata":"RPR"},
  "dhanbad": {"station":"DHN","iata":"RDP"},
  "dhar": {"station":"INDB","iata":"IDR"},
  "dharmapuri": {"station":"DPJ","iata":"BLR"},
  "dharwad": {"station":"DWR","iata":"HBX"},
  "dhemaji": {"station":"DMC","iata":"DIB"},
  "dhenkanal": {"station":"DNKL","iata":"BBI"},
  "dholpur": {"station":"AGC","iata":"GWL"},
  "dhubri": {"station":"DBB","iata":"GAU"},
  "dhule": {"station":"DHI","iata":"ISK"},
  "dibang valley": {"iata":"DIB"},
  "dibrugarh": {"station":"DBRG","iata":"DIB"},
  "dima hasao": {"station":"GHY","iata":"IXS"},
  "dimapur": {"station":"DMV","iata":"DMU"},
  "dinajpur dakshin": {"iata":"IXB"},
  "dinajpur uttar": {"iata":"IXB"},
  "dindigul": {"station":"DFG","iata":"IXM"},
  "dindori": {"station":"PRYJ","iata":"JLR"},
  "diu": {"station":"RJT","iata":"DIU"},
  "doda": {"station":"JAT","iata":"IXP"},
  "dohad": {"station":"BRC","iata":"BDQ"},
  "dumka": {"station":"DUMK","iata":"RDP"},
  "dungarpur": {"station":"DNRP","iata":"UDR"},
  "durg": {"station":"DURG","iata":"RPR"},
  "east": {"station":"NDLS","iata":"DEL"},
  "east district": {"iata":"IXB"},
  "east garo hills": {"station":"GHY","iata":"GAU"},
  "east godavari": {"station":"BZA","iata":"RJA"},
  "east jaintia hills": {"station":"GHY","iata":"SHL"},
  "east kameng": {"station":"GHY","iata":"TEZ"},
  "east khasi hills": {"station":"GHY","iata":"SHL"},
  "east nimar": {"station":"KNW","iata":"IDR"},
  "east siang": {"iata":"DIB"},
  "east singhbum": {"station":"RNC","iata":"IXR"},
  "eluru": {"station":"EE","iata":"VGA"},
  "ernakulam": {"station":"ERG","iata":"COK"},
  "erode": {"station":"ED","iata":"CJB"},
  "etah": {"station":"ETAH","iata":"GWL"},
  "etawah": {"station":"ETW","iata":"GWL"},
  "faridabad": {"station":"FDB","iata":"DEL"},
  "faridkot": {"station":"FDK","iata":"ATQ"},
  "farrukhabad": {"station":"FBD","iata":"LKO"},
  "fatehabad": {"station":"LDH","iata":"IXC"},
  "fatehgarh sahib": {"station":"FGSB","iata":"IXC"},
  "fatehpur": {"station":"FTP","iata":"LKO"},
  "fazilka": {"station":"FKA","iata":"ATQ"},
  "firozabad": {"station":"FZD","iata":"GWL"},
  "firozepur": {"station":"ASR","iata":"ATQ"},
  "gadag": {"station":"GDG","iata":"HBX"},
  "gadchiroli": {"station":"NGP","iata":"NAG"},
  "gajapati": {"station":"VSKP","iata":"VTZ"},
  "ganderbal": {"station":"JAT","iata":"SXR"},
  "gandhinagar": {"station":"ADI","iata":"AMD"},
  "ganganagar": {"station":"LDH","iata":"ATQ"},
  "ganjam": {"station":"GAM","iata":"BBI"},
  "garhwa": {"station":"GHQ","iata":"GAY"},
  "gariyaband": {"station":"R","iata":"RPR"},
  "gaurella pendra marwahi": {"station":"R","iata":"RPR"},
  "gautam buddha nagar": {"station":"DER","iata":"DEL"},
  "gaya": {"station":"GAYA","iata":"GAY"},
  "ghaziabad": {"station":"GZB","iata":"DEL"},
  "ghazipur": {"station":"GCT","iata":"VNS"},
  "gir somnath": {"station":"RJT","iata":"DIU"},
  "giridih": {"station":"RNC","iata":"GAY"},
  "goalpara": {"station":"GHY","iata":"GAU"},
  "godda": {"station":"PNBE","iata":"RDP"},
  "golaghat": {"station":"GHY","iata":"JRH"},
  "gomati": {"iata":"IXA"},
  "gonda": {"station":"GD","iata":"LKO"},
  "gondia": {"station":"G","iata":"NAG"},
  "gopalganj": {"station":"GOPG","iata":"GOP"},
  "gorakhpur": {"station":"GJPC","iata":"GOP"},
  "gumla": {"station":"RNC","iata":"IXR"},
  "guna": {"station":"GUNA","iata":"BHO"},
  "guntur": {"station":"GNT","iata":"VGA"},
  "gurdaspur": {"station":"GSP","iata":"ATQ"},
  "gurugram": {"station":"NDLS","iata":"DEL"},
  "gwalior": {"station":"GWL","iata":"GWL"},
  "hailakandi": {"station":"HKD","iata":"SHL"},
  "hamirpur": {"station":"HW","iata":"DED"},
  "hanumakonda": {"station":"SC","iata":"HYD"},
  "hanumangarh": {"station":"HMH","iata":"DEL"},
  "hapur": {"station":"HPU","iata":"DEL"},
  "harda": {"station":"HD","iata":"BHO"},
  "hardoi": {"station":"HRI","iata":"LKO"},
  "haridwar": {"station":"HW","iata":"DED"},
  "hassan": {"station":"HAS","iata":"IXE"},
  "hathras": {"station":"HRS","iata":"GWL"},
  "haveri": {"station":"HVR","iata":"HBX"},
  "hazaribagh": {"station":"HHZBN","iata":"IXR"},
  "hingoli": {"station":"AWB","iata":"NDC"},
  "hisar": {"station":"NDLS","iata":"DEL"},
  "hnahthial": {"iata":"AJL"},
  "hojai": {"station":"HJI","iata":"TEZ"},
  "hooghly": {"station":"HGY","iata":"CCU"},
  "hoshangabad": {"station":"HBD","iata":"BHO"},
  "hoshiarpur": {"station":"HSX","iata":"AIP"},
  "howrah": {"station":"HJN","iata":"CCU"},
  "hyderabad": {"station":"SC","iata":"HYD"},
  "idukki": {"station":"ERS","iata":"COK"},
  "imphal east": {"iata":"IMF"},
  "imphal west": {"station":"GHY","iata":"IMF"},
  "indore": {"station":"INDB","iata":"IDR"},
  "jabalpur": {"station":"JBP","iata":"JLR"},
  "jagatsinghapur": {"station":"BBS","iata":"BBI"},
  "jagitial": {"station":"SC","iata":"NDC"},
  "jaipur": {"station":"JP","iata":"JAI"},
  "jaisalmer": {"station":"JSM","iata":"JDH"},
  "jajapur": {"station":"BBS","iata":"BBI"},
  "jalandhar": {"station":"JRC","iata":"AIP"},
  "jalaun": {"station":"VGLJ","iata":"GWL"},
  "jalgaon": {"station":"JL","iata":"IXU"},
  "jalna": {"station":"J","iata":"IXU"},
  "jalore": {"station":"JU","iata":"JDH"},
  "jalpaiguri": {"station":"JPG","iata":"IXB"},
  "jammu": {"station":"JAT","iata":"IXJ"},
  "jamnagar": {"station":"RJT","iata":"JGA"},
  "jamtara": {"station":"JMT","iata":"RDP"},
  "jamui": {"station":"JMU","iata":"GAY"},
  "jangoan": {"station":"SC","iata":"HYD"},
  "janjgir-champa": {"station":"R","iata":"RPR"},
  "jashpur": {"station":"RNC","iata":"IXR"},
  "jaunpur": {"station":"JNU","iata":"VNS"},
  "jayashankar bhupalapally": {"station":"SC","iata":"HYD"},
  "jehanabad": {"station":"JHD","iata":"GAY"},
  "jhabua": {"station":"INDB","iata":"IDR"},
  "jhajjar": {"station":"JHJ","iata":"DEL"},
  "jhalawar": {"station":"BPL","iata":"BHO"},
  "jhansi": {"station":"JHS","iata":"GWL"},
  "jhargram": {"station":"HWH","iata":"RDP"},
  "jharsuguda": {"station":"JSG","iata":"IXR"},
  "jhunjhunu": {"station":"JJN","iata":"JAI"},
  "jind": {"station":"JCY","iata":"DEL"},
  "jiribam": {"station":"JRBM","iata":"IXS"},
  "jodhpur": {"station":"JU","iata":"JDH"},
  "jogulamba gadwal": {"station":"SC","iata":"HYD"},
  "jorhat": {"station":"JT","iata":"JRH"},
  "junagadh": {"station":"JND","iata":"PBD"},
  "kabirdham": {"station":"R","iata":"RPR"},
  "kachchh": {"station":"BHUJ","iata":"BHJ"},
  "kaimur (bhabua)": {"station":"BSB","iata":"VNS"},
  "kaithal": {"station":"KLE","iata":"IXC"},
  "kakching": {"iata":"IMF"},
  "kakinada": {"station":"CCT","iata":"RJA"},
  "kalaburagi": {"station":"KLBG","iata":"LTU"},
  "kalahandi": {"station":"R","iata":"RPR"},
  "kalimpong": {"iata":"IXB"},
  "kallakurichi": {"station":"MAS","iata":"TRZ"},
  "kamareddy": {"station":"SC","iata":"HYD"},
  "kamjong": {"iata":"IMF"},
  "kamle": {"iata":"IXI"},
  "kamrup": {"station":"GHY","iata":"GAU"},
  "kamrup metro": {"station":"GHY","iata":"GAU"},
  "kanchipuram": {"station":"CJ","iata":"MAA"},
  "kandhamal": {"station":"BBS","iata":"BBI"},
  "kangpokpi": {"station":"GHY","iata":"IMF"},
  "kangra": {"station":"KGRA","iata":"IXP"},
  "kanker": {"station":"R","iata":"RPR"},
  "kannauj": {"station":"KJN","iata":"LKO"},
  "kanniyakumari": {"station":"TVC","iata":"TRV"},
  "kannur": {"station":"MAQ","iata":"CNN"},
  "kanpur dehat": {"station":"CNB","iata":"LKO"},
  "kanpur nagar": {"station":"CNB","iata":"LKO"},
  "kapurthala": {"station":"KXH","iata":"AIP"},
  "karaikal": {"station":"KIK","iata":"TRZ"},
  "karauli": {"station":"JP","iata":"JAI"},
  "karbi anglong": {"station":"GHY","iata":"DMU"},
  "kargil": {"station":"JAT","iata":"IXL"},
  "karimganj": {"station":"KXJ","iata":"IXS"},
  "karimnagar": {"station":"SC","iata":"HYD"},
  "karnal": {"station":"KUN","iata":"DEL"},
  "karur": {"station":"KRR","iata":"TRZ"},
  "kasaragod": {"station":"KGQ","iata":"IXE"},
  "kasganj": {"station":"KJC","iata":"GWL"},
  "kathua": {"station":"KTHU","iata":"IXP"},
  "katihar": {"station":"KIR","iata":"IXB"},
  "katni": {"station":"KTE","iata":"JLR"},
  "kaushambi": {"station":"PRYJ","iata":"LKO"},
  "kendrapara": {"station":"BBS","iata":"BBI"},
  "kendujhar": {"station":"KDJR","iata":"BBI"},
  "khagaria": {"station":"KGG","iata":"PAT"},
  "khammam": {"station":"KMT","iata":"VGA"},
  "khargone": {"station":"INDB","iata":"IDR"},
  "khawzawl": {"iata":"AJL"},
  "kheda": {"station":"NK","iata":"ISK"},
  "kheri": {"station":"LKO","iata":"LKO"},
  "khordha": {"station":"BBS","iata":"BBI"},
  "khowai": {"station":"GHY","iata":"IXA"},
  "khunti": {"station":"RNC","iata":"IXR"},
  "kinnaur": {"station":"DDN","iata":"DED"},
  "kiphire": {"iata":"DMU"},
  "kishanganj": {"station":"KNE","iata":"IXB"},
  "kishtwar": {"station":"JAT","iata":"IXJ"},
  "kodagu": {"station":"MYS","iata":"CNN"},
  "koderma": {"station":"KQR","iata":"GAY"},
  "kohima": {"station":"GHY","iata":"DMU"},
  "kokrajhar": {"station":"KKRJ","iata":"GAU"},
  "kolar": {"station":"KQZ","iata":"BLR"},
  "kolasib": {"station":"GHY","iata":"AJL"},
  "kolhapur": {"station":"KOP","iata":"KLH"},
  "kolkata": {"station":"KOAA","iata":"CCU"},
  "kollam": {"station":"TVC","iata":"TRV"},
  "konaseema": {"station":"BZA","iata":"RJA"},
  "kondagaon": {"station":"R","iata":"RPR"},
  "koppal": {"station":"KBL","iata":"HBX"},
  "koraput": {"station":"KRPU","iata":"VTZ"},
  "korba": {"station":"KRBA","iata":"RPR"},
  "korea": {"station":"BSB","iata":"TNI"},
  "kota": {"station":"KOTA","iata":"JAI"},
  "kottayam": {"station":"KTYM","iata":"CJB"},
  "kozhikode": {"station":"MYS","iata":"CCJ"},
  "kra daadi": {"station":"GHY","iata":"IXI"},
  "krishna": {"station":"KSN","iata":"VGA"},
  "krishnagiri": {"station":"SBC","iata":"BLR"},
  "kulgam": {"station":"JAT","iata":"SXR"},
  "kullu": {"station":"CDG","iata":"IXC"},
  "kumuram bheem asifabad": {"station":"NGP","iata":"NAG"},
  "kupwara": {"station":"JAT","iata":"SXR"},
  "kurnool": {"station":"KRNT","iata":"CDP"},
  "kurukshetra": {"station":"KKDE","iata":"IXC"},
  "kurung kumey": {"station":"GHY","iata":"IXI"},
  "kushi nagar": {"station":"GKP","iata":"GOP"},
  "lahul and spiti": {"station":"CDG","iata":"IXP"},
  "lakhimpur": {"station":"LMP","iata":"IXI"},
  "lakhisarai": {"station":"PNBE","iata":"PAT"},
  "lakshadweep district": {"iata":"CNN"},
  "lalitpur": {"station":"LAR","iata":"HJR"},
  "latehar": {"station":"RNC","iata":"IXR"},
  "latur": {"station":"LUR","iata":"LTU"},
  "lawngtlai": {"iata":"AJL"},
  "leh ladakh": {"iata":"IXL"},
  "leparada": {"iata":"DIB"},
  "lohardaga": {"station":"LAD","iata":"IXR"},
  "lohit": {"iata":"DIB"},
  "longding": {"iata":"DIB"},
  "longleng": {"iata":"JRH"},
  "lower dibang valley": {"iata":"DIB"},
  "lower siang": {"iata":"DIB"},
  "lower subansiri": {"station":"GHY","iata":"IXI"},
  "lucknow": {"station":"AMV","iata":"LKO"},
  "ludhiana": {"station":"LDH","iata":"IXC"},
  "lunglei": {"iata":"AJL"},
  "madhepura": {"station":"PNBE","iata":"PAT"},
  "madhubani": {"station":"MBI","iata":"PAT"},
  "madurai": {"station":"MDRJ","iata":"IXM"},
  "mahabubabad": {"station":"BZA","iata":"VGA"},
  "mahabubnagar": {"station":"SC","iata":"HYD"},
  "maharajganj": {"station":"GKP","iata":"GOP"},
  "mahasamund": {"station":"MSMD","iata":"RPR"},
  "mahe": {"station":"MAHE","iata":"CNN"},
  "mahendragarh": {"station":"NDLS","iata":"DEL"},
  "mahesana": {"station":"MSH","iata":"AMD"},
  "mahisagar": {"station":"BRC","iata":"BDQ"},
  "mahoba": {"station":"MBA","iata":"HJR"},
  "mainpuri": {"station":"MNQ","iata":"GWL"},
  "majuli": {"station":"GHY","iata":"JRH"},
  "malappuram": {"station":"CBE","iata":"CCJ"},
  "maldah": {"iata":"IXB"},
  "malerkotla": {"station":"MET","iata":"DEL"},
  "malkangiri": {"station":"VSKP","iata":"VTZ"},
  "mamit": {"iata":"AJL"},
  "mancherial": {"station":"SC","iata":"HYD"},
  "mandi": {"station":"CDG","iata":"IXC"},
  "mandla": {"station":"VGLJ","iata":"JLR"},
  "mandsaur": {"station":"INDB","iata":"IDR"},
  "mandya": {"station":"MYA","iata":"BLR"},
  "mansa": {"station":"MSZ","iata":"IXC"},
  "marigaon": {"station":"GHY","iata":"TEZ"},
  "mathura": {"station":"MRT","iata":"DEL"},
  "mau": {"station":"MAU","iata":"VNS"},
  "mayiladuthurai": {"station":"MDU","iata":"TRZ"},
  "mayurbhanj": {"station":"HWH","iata":"BBI"},
  "medak": {"station":"SC","iata":"HYD"},
  "medchal malkajgiri": {"station":"SC","iata":"HYD"},
  "medinipur east": {"station":"HWH","iata":"CCU"},
  "medinipur west": {"station":"HWH","iata":"CCU"},
  "meerut": {"station":"MTC","iata":"DEL"},
  "mirzapur": {"station":"MZP","iata":"VNS"},
  "moga": {"station":"MOGA","iata":"AIP"},
  "mokokchung": {"iata":"JRH"},
  "mon": {"iata":"JRH"},
  "moradabad": {"station":"MB","iata":"DEL"},
  "morbi": {"station":"MVI","iata":"RAJ"},
  "morena": {"station":"MRA","iata":"GWL"},
  "mulugu": {"station":"SC","iata":"HYD"},
  "mumbai": {"station":"BY","iata":"BOM"},
  "mumbai suburban": {"station":"CSMT","iata":"BOM"},
  "mungeli": {"station":"R","iata":"RPR"},
  "munger": {"station":"PNBE","iata":"PAT"},
  "murshidabad": {"station":"MBB","iata":"RDP"},
  "muzaffarnagar": {"station":"MOZ","iata":"DED"},
  "muzaffarpur": {"station":"MFP","iata":"PAT"},
  "mysuru": {"station":"MYS","iata":"CNN"},
  "nabarangpur": {"station":"R","iata":"RPR"},
  "nadia": {"station":"HWH","iata":"CCU"},
  "nagaon": {"station":"NGAN","iata":"TEZ"},
  "nagapattinam": {"station":"MDU","iata":"TRZ"},
  "nagarkurnool": {"station":"SC","iata":"HYD"},
  "nagaur": {"station":"NGO","iata":"KQH"},
  "nagpur": {"station":"MIB","iata":"NAG"},
  "nainital": {"station":"HW","iata":"DED"},
  "nalanda": {"station":"NLD","iata":"PAT"},
  "nalbari": {"station":"NLAI","iata":"GAU"},
  "nalgonda": {"station":"NLDA","iata":"HYD"},
  "namakkal": {"station":"NMKL","iata":"TRZ"},
  "namsai": {"iata":"DIB"},
  "nanded": {"station":"NED","iata":"NDC"},
  "nandurbar": {"station":"NDB","iata":"BDQ"},
  "nandyal": {"station":"NDL","iata":"CDP"},
  "narayanpet": {"station":"SC","iata":"HYD"},
  "narayanpur": {"station":"NNR","iata":"RPR"},
  "narmada": {"station":"ST","iata":"STV"},
  "narsinghpur": {"station":"NU","iata":"JLR"},
  "nashik": {"station":"NK","iata":"ISK"},
  "navsari": {"station":"NVS","iata":"STV"},
  "nawada": {"station":"PNBE","iata":"GAY"},
  "nayagarh": {"station":"NYG","iata":"BBI"},
  "neemuch": {"station":"UDZ","iata":"UDR"},
  "new delhi": {"station":"NDLS","iata":"DEL"},
  "nicobars": {"iata":"IXZ"},
  "nirmal": {"station":"SC","iata":"NDC"},
  "niwari": {"station":"VGLJ","iata":"HJR"},
  "nizamabad": {"station":"NZB","iata":"NDC"},
  "noklak": {"iata":"JRH"},
  "noney": {"station":"GHY","iata":"IMF"},
  "north": {"station":"NDLS","iata":"DEL"},
  "north and middle andaman": {"iata":"IXZ"},
  "north district": {"iata":"IXB"},
  "north east": {"station":"NDLS","iata":"DEL"},
  "north garo hills": {"station":"GHY","iata":"GAU"},
  "north goa": {"station":"MAO","iata":"GOI"},
  "north tripura": {"station":"GHY","iata":"AJL"},
  "north west": {"station":"NDLS","iata":"DEL"},
  "ntr": {"station":"BZA","iata":"VGA"},
  "nuapada": {"station":"R","iata":"RPR"},
  "nuh": {"station":"NDLS","iata":"DEL"},
  "osmanabad": {"station":"AWB","iata":"LTU"},
  "pakke kessang": {"station":"GHY","iata":"TEZ"},
  "pakur": {"station":"HWH","iata":"RDP"},
  "pakyong": {"iata":"IXB"},
  "palakkad": {"station":"MYS","iata":"CNN"},
  "palamu": {"station":"RNC","iata":"GAY"},
  "palghar": {"station":"PLG","iata":"BOM"},
  "pali": {"station":"PALI","iata":"JDH"},
  "palnadu": {"station":"BZA","iata":"VGA"},
  "palwal": {"station":"PWL","iata":"DEL"},
  "panch mahals": {"station":"BRC","iata":"BDQ"},
  "panchkula": {"station":"CDG","iata":"IXC"},
  "panipat": {"station":"PNP","iata":"DEL"},
  "panna": {"station":"VGLJ","iata":"HJR"},
  "papum pare": {"station":"GHY","iata":"IXI"},
  "parbhani": {"station":"PBN","iata":"NDC"},
  "parvathipuram manyam": {"station":"VSKP","iata":"VTZ"},
  "paschim bardhaman": {"station":"RNC","iata":"RDP"},
  "pashchim champaran": {"station":"GKP","iata":"GOP"},
  "patan": {"station":"PTN","iata":"BOM"},
  "pathanamthitta": {"station":"ERS","iata":"TRV"},
  "pathankot": {"station":"PTK","iata":"IXP"},
  "patiala": {"station":"PTA","iata":"IXC"},
  "patna": {"station":"PNBE","iata":"PAT"},
  "pauri garhwal": {"station":"HW","iata":"DED"},
  "peddapalli": {"station":"PDPL","iata":"HYD"},
  "perambalur": {"station":"MDU","iata":"TRZ"},
  "peren": {"station":"GHY","iata":"DMU"},
  "phek": {"station":"GHY","iata":"DMU"},
  "pherzawl": {"station":"GHY","iata":"IMF"},
  "pilibhit": {"station":"PBE","iata":"LKO"},
  "pithoragarh": {"station":"HW","iata":"DED"},
  "pondicherry": {"station":"PDY","iata":"MAA"},
  "poonch": {"station":"JAT","iata":"SXR"},
  "porbandar": {"station":"PBR","iata":"PBD"},
  "prakasam": {"station":"BZA","iata":"CDP"},
  "pratapgarh": {"station":"NGP","iata":"JLR"},
  "prayagraj": {"station":"PRYJ","iata":"VNS"},
  "pudukkottai": {"station":"PDKT","iata":"TRZ"},
  "pulwama": {"station":"JAT","iata":"SXR"},
  "pune": {"station":"PUNE","iata":"PNQ"},
  "purba bardhaman": {"station":"HWH","iata":"RDP"},
  "purbi champaran": {"station":"PNBE","iata":"PAT"},
  "puri": {"station":"PURI","iata":"BBI"},
  "purnia": {"station":"PRNA","iata":"IXB"},
  "purulia": {"station":"PRR","iata":"RDP"},
  "rae bareli": {"station":"RBL","iata":"LKO"},
  "raichur": {"station":"RC","iata":"HYD"},
  "raigad": {"station":"CSMT","iata":"PNQ"},
  "raigarh": {"station":"RIG","iata":"RPR"},
  "raipur": {"station":"R","iata":"RPR"},
  "raisen": {"station":"BPL","iata":"BHO"},
  "rajanna sircilla": {"station":"SC","iata":"HYD"},
  "rajgarh": {"station":"RHG","iata":"BHO"},
  "rajkot": {"station":"RJON","iata":"RAJ"},
  "rajnandgaon": {"station":"RJN","iata":"RPR"},
  "rajouri": {"station":"JAT","iata":"IXJ"},
  "rajsamand": {"station":"UDZ","iata":"UDR"},
  "ramanagara": {"station":"SBC","iata":"BLR"},
  "ramanathapuram": {"station":"RMD","iata":"IXM"},
  "ramban": {"station":"JAT","iata":"IXJ"},
  "ramgarh": {"station":"RAH","iata":"IXR"},
  "rampur": {"station":"RMPB","iata":"DED"},
  "ranchi": {"station":"RNC","iata":"IXR"},
  "ranga reddy": {"station":"SC","iata":"HYD"},
  "ranipet": {"station":"TPTY","iata":"TIR"},
  "ratlam": {"station":"RTLM","iata":"IDR"},
  "ratnagiri": {"station":"RN","iata":"KLH"},
  "rayagada": {"station":"RGDA","iata":"VTZ"},
  "reasi": {"station":"JAT","iata":"IXJ"},
  "rewa": {"station":"REWA","iata":"TNI"},
  "rewari": {"station":"RE","iata":"DEL"},
  "ri bhoi": {"station":"GHY","iata":"SHL"},
  "rohtak": {"station":"ROK","iata":"DEL"},
  "rohtas": {"station":"BSB","iata":"GAY"},
  "rudra prayag": {"station":"HW","iata":"DED"},
  "rupnagar": {"station":"RPAR","iata":"IXC"},
  "s.a.s nagar": {"station":"CDG","iata":"IXC"},
  "sabar kantha": {"station":"ADI","iata":"AMD"},
  "sagar": {"station":"BPL","iata":"JLR"},
  "saharanpur": {"station":"SRE","iata":"DED"},
  "saharsa": {"station":"SHC","iata":"PAT"},
  "sahebganj": {"station":"PNBE","iata":"RDP"},
  "saiha": {"iata":"AJL"},
  "saitual": {"iata":"AJL"},
  "salem": {"station":"SA","iata":"TRZ"},
  "samastipur": {"station":"SMSP","iata":"PAT"},
  "samba": {"station":"SMBX","iata":"IXJ"},
  "sambalpur": {"station":"SBP","iata":"BBI"},
  "sambhal": {"station":"NDLS","iata":"DEL"},
  "sangareddy": {"station":"SC","iata":"HYD"},
  "sangli": {"station":"SLI","iata":"KLH"},
  "sangrur": {"station":"SAG","iata":"IXC"},
  "sant kabeer nagar": {"station":"GKP","iata":"GOP"},
  "saraikela kharsawan": {"station":"RNC","iata":"IXR"},
  "saran": {"station":"PNBE","iata":"PAT"},
  "satara": {"station":"STR","iata":"PNQ"},
  "satna": {"station":"STA","iata":"TNI"},
  "sawai madhopur": {"station":"SWM","iata":"JAI"},
  "sehore": {"station":"SEH","iata":"BHO"},
  "senapati": {"station":"GHY","iata":"DMU"},
  "seoni": {"station":"SEY","iata":"JLR"},
  "sepahijala": {"station":"HWH","iata":"CCU"},
  "serchhip": {"iata":"AJL"},
  "shahdara": {"station":"NDLS","iata":"DEL"},
  "shahdol": {"station":"SDL","iata":"TNI"},
  "shahid bhagat singh nagar": {"station":"LDH","iata":"AIP"},
  "shahjahanpur": {"station":"SPN","iata":"LKO"},
  "shajapur": {"station":"SFY","iata":"BHO"},
  "shamli": {"station":"SMQL","iata":"DEL"},
  "sheikhpura": {"station":"PNBE","iata":"PAT"},
  "sheohar": {"station":"PNBE","iata":"PAT"},
  "sheopur": {"station":"GWL","iata":"GWL"},
  "shi yomi": {"iata":"IXI"},
  "shimla": {"station":"SML","iata":"IXC"},
  "shivamogga": {"station":"MAQ","iata":"IXE"},
  "shivpuri": {"station":"SPHT","iata":"GWL"},
  "shopian": {"station":"JAT","iata":"SXR"},
  "shravasti": {"station":"LKO","iata":"LKO"},
  "siang": {"iata":"DIB"},
  "siddharth nagar": {"station":"SDDN","iata":"GOP"},
  "siddipet": {"station":"SC","iata":"HYD"},
  "sidhi": {"station":"PRYJ","iata":"TNI"},
  "sikar": {"station":"SIKR","iata":"JAI"},
  "simdega": {"station":"RNC","iata":"IXR"},
  "sindhudurg": {"station":"MAO","iata":"GOI"},
  "singrauli": {"station":"SGRL","iata":"TNI"},
  "sirmaur": {"station":"CDG","iata":"IXC"},
  "sirohi": {"station":"UDZ","iata":"UDR"},
  "sirsa": {"station":"SSA","iata":"IXC"},
  "sitamarhi": {"station":"SMI","iata":"PAT"},
  "sitapur": {"station":"SPC","iata":"LKO"},
  "sivaganga": {"station":"SVGA","iata":"IXM"},
  "sivasagar": {"station":"GHY","iata":"DMU"},
  "siwan": {"station":"SV","iata":"PAT"},
  "solan": {"station":"SOL","iata":"IXC"},
  "solapur": {"station":"SUR","iata":"LTU"},
  "sonbhadra": {"station":"SBDR","iata":"VNS"},
  "sonepur": {"station":"BBS","iata":"RPR"},
  "sonipat": {"station":"SNP","iata":"DEL"},
  "sonitpur": {"station":"GHY","iata":"TEZ"},
  "soreng": {"iata":"IXB"},
  "south": {"station":"NDLS","iata":"DEL"},
  "south andamans": {"iata":"IXZ"},
  "south district": {"iata":"IXB"},
  "south east": {"station":"NDLS","iata":"DEL"},
  "south garo hills": {"station":"GHY","iata":"GAU"},
  "south goa": {"station":"MAO","iata":"GOI"},
  "south salmara mancachar": {"station":"GHY","iata":"GAU"},
  "south tripura": {"iata":"IXA"},
  "south west": {"station":"AGC","iata":"DEL"},
  "south west garo hills": {"station":"GHY","iata":"GAU"},
  "south west khasi hills": {"station":"GHY","iata":"SHL"},
  "spsr nellore": {"station":"TPTY","iata":"TIR"},
  "sri muktsar sahib": {"station":"LDH","iata":"ATQ"},
  "sri sathya sai": {"station":"SBC","iata":"BLR"},
  "srikakulam": {"station":"VSKP","iata":"VTZ"},
  "srinagar": {"station":"SINA","iata":"SXR"},
  "sukma": {"station":"VSKP","iata":"RJA"},
  "sultanpur": {"station":"SLN","iata":"VNS"},
  "sundargarh": {"station":"RNC","iata":"IXR"},
  "supaul": {"station":"SOU","iata":"PAT"},
  "surajpur": {"station":"SUPR","iata":"VNS"},
  "surat": {"station":"ST","iata":"STV"},
  "surendranagar": {"station":"SNNR","iata":"RAJ"},
  "surguja": {"station":"RNC","iata":"IXR"},
  "suryapet": {"station":"BZA","iata":"VGA"},
  "tamenglong": {"station":"GHY","iata":"IMF"},
  "tapi": {"station":"ST","iata":"STV"},
  "tarn taran": {"station":"TTO","iata":"ATQ"},
  "tawang": {"station":"GHY","iata":"TEZ"},
  "tehri garhwal": {"station":"DDN","iata":"DED"},
  "tengnoupal": {"iata":"IMF"},
  "tenkasi": {"station":"TSI","iata":"TCR"},
  "thane": {"station":"TNA","iata":"BOM"},
  "thanjavur": {"station":"TJ","iata":"TRZ"},
  "the nilgiris": {"station":"CBE","iata":"CJB"},
  "theni": {"station":"MDU","iata":"IXM"},
  "thiruvallur": {"station":"MAS","iata":"MAA"},
  "thiruvananthapuram": {"station":"TVC","iata":"TRV"},
  "thiruvarur": {"station":"TVR","iata":"TRZ"},
  "thoubal": {"iata":"IMF"},
  "thrissur": {"station":"ERS","iata":"COK"},
  "tikamgarh": {"station":"VGLJ","iata":"HJR"},
  "tinsukia": {"station":"TSK","iata":"DIB"},
  "tirap": {"iata":"DIB"},
  "tiruchirappalli": {"station":"TCPP","iata":"TRZ"},
  "tirunelveli": {"station":"TEN","iata":"TCR"},
  "tirupathur": {"station":"SBC","iata":"BLR"},
  "tirupati": {"station":"TPTY","iata":"TIR"},
  "tiruppur": {"station":"TUP","iata":"CJB"},
  "tiruvannamalai": {"station":"TNM","iata":"MAA"},
  "tonk": {"station":"JP","iata":"JAI"},
  "tuensang": {"station":"GHY","iata":"JRH"},
  "tumakuru": {"station":"SBC","iata":"BLR"},
  "tuticorin": {"station":"TN","iata":"TCR"},
  "udaipur": {"station":"UDPU","iata":"UDR"},
  "udalguri": {"station":"GHY","iata":"TEZ"},
  "udam singh nagar": {"station":"HW","iata":"DED"},
  "udhampur": {"station":"UHM","iata":"IXJ"},
  "udupi": {"station":"MAQ","iata":"IXE"},
  "ujjain": {"station":"UJJN","iata":"IDR"},
  "ukhrul": {"iata":"IMF"},
  "umaria": {"station":"UMR","iata":"JLR"},
  "una": {"station":"UNA","iata":"AIP"},
  "unakoti": {"station":"GHY","iata":"AJL"},
  "unnao": {"station":"ON","iata":"LKO"},
  "upper siang": {"iata":"DIB"},
  "upper subansiri": {"iata":"IXI"},
  "uttar kashi": {"station":"DDN","iata":"DED"},
  "uttara kannada": {"station":"MAO","iata":"HBX"},
  "vadodara": {"station":"PUNE","iata":"PNQ"},
  "vaishali": {"station":"PNBE","iata":"PAT"},
  "valsad": {"station":"BL","iata":"STV"},
  "varanasi": {"station":"BCY","iata":"VNS"},
  "vellore": {"station":"VLR","iata":"TIR"},
  "vidisha": {"station":"BHS","iata":"BHO"},
  "vijayapura": {"station":"MAO","iata":"IXG"},
  "vijaynagar": {"station":"MAO","iata":"HBX"},
  "vikarabad": {"station":"SC","iata":"HYD"},
  "villupuram": {"station":"VM","iata":"MAA"},
  "virudhunagar": {"station":"VDDR","iata":"IXM"},
  "visakhapatanam": {"station":"VSKP","iata":"VTZ"},
  "vizianagaram": {"station":"VZM","iata":"VTZ"},
  "wanaparthy": {"station":"SC","iata":"HYD"},
  "warangal": {"station":"WL","iata":"HYD"},
  "wardha": {"station":"WR","iata":"NAG"},
  "washim": {"station":"WHM","iata":"NDC"},
  "wayanad": {"station":"MYS","iata":"CCJ"},
  "west": {"station":"NDLS","iata":"DEL"},
  "west district": {"iata":"IXB"},
  "west garo hills": {"station":"GHY","iata":"GAU"},
  "west godavari": {"station":"BZA","iata":"RJA"},
  "west jaintia hills": {"station":"GHY","iata":"SHL"},
  "west kameng": {"station":"GHY","iata":"TEZ"},
  "west karbi anglong": {"station":"GHY","iata":"SHL"},
  "west khasi hills": {"station":"GHY","iata":"GAU"},
  "west siang": {"iata":"DIB"},
  "west singhbhum": {"station":"RNC","iata":"IXR"},
  "west tripura": {"station":"GHY","iata":"IXA"},
  "wokha": {"station":"GHY","iata":"DMU"},
  "y.s.r.": {"station":"TPTY","iata":"CDP"},
  "yadadri bhuvanagiri": {"station":"SC","iata":"HYD"},
  "yadgir": {"station":"YG","iata":"HYD"},
  "yamunanagar": {"station":"CDG","iata":"IXC"},
  "yanam": {"station":"VSKP","iata":"RJA"},
  "yavatmal": {"station":"YTL","iata":"NDC"},
  "zunheboto": {"iata":"DMU"},
};
