// City name -> IATA airport code, for the flight adapter (Duffel needs codes)
// and Skyscanner deep links. Extend as more routes are added.

import { DISTRICT_HUBS } from "@/lib/district-hubs";

const IATA: Record<string, string> = {
  "andaman": "IXZ",
  "port blair": "IXZ",
  agartala: "IXA",
  agra: "AGR",
  ahmedabad: "AMD",
  amritsar: "ATQ",
  aurangabad: "IXU",
  bagdogra: "IXB",
  siliguri: "IXB",
  bangalore: "BLR",
  bengaluru: "BLR",
  bhopal: "BHO",
  bhubaneswar: "BBI",
  chandigarh: "IXC",
  chennai: "MAA",
  cochin: "COK",
  coimbatore: "CJB",
  dehradun: "DED",
  delhi: "DEL",
  "new delhi": "DEL",
  dibrugarh: "DIB",
  gaya: "GAY",
  goa: "GOI",
  guwahati: "GAU",
  gwalior: "GWL",
  hubli: "HBX",
  hyderabad: "HYD",
  imphal: "IMF",
  indore: "IDR",
  jaipur: "JAI",
  jammu: "IXJ",
  jodhpur: "JDH",
  kanpur: "KNU",
  kochi: "COK",
  kolkata: "CCU",
  kozhikode: "CCJ",
  calicut: "CCJ",
  leh: "IXL",
  lucknow: "LKO",
  madurai: "IXM",
  mangalore: "IXE",
  mangaluru: "IXE",
  mumbai: "BOM",
  mysore: "MYQ",
  mysuru: "MYQ",
  nagpur: "NAG",
  nashik: "ISK",
  patna: "PAT",
  pune: "PNQ",
  raipur: "RPR",
  rajkot: "RAJ",
  ranchi: "IXR",
  shillong: "SHL",
  srinagar: "SXR",
  surat: "STV",
  tirupati: "TIR",
  trivandrum: "TRV",
  thiruvananthapuram: "TRV",
  udaipur: "UDR",
  vadodara: "BDQ",
  varanasi: "VNS",
  vijayawada: "VGA",
  visakhapatnam: "VTZ",
  vizag: "VTZ",
};

export function toIata(city: string): string | null {
  const key = city.trim().toLowerCase();
  // direct city -> airport, else the nearest airport to that district's centre
  return IATA[key] ?? DISTRICT_HUBS[key]?.iata ?? null;
}
