// City name -> IATA airport code, for the flight adapter (Duffel needs codes)
// and Skyscanner deep links. Extend as more routes are added.

import { DISTRICT_HUBS } from "@/lib/district-hubs";

const IATA: Record<string, string> = {
  "andaman": "IXZ",
  "port blair": "IXZ",
  agartala: "IXA",
  agra: "AGR",
  ahmedabad: "AMD",
  amritsar: "ATQ",
  aurangabad: "IXU",
  bagdogra: "IXB",
  siliguri: "IXB",
  bangalore: "BLR",
  bengaluru: "BLR",
  bhopal: "BHO",
  bhubaneswar: "BBI",
  chandigarh: "IXC",
  chennai: "MAA",
  cochin: "COK",
  coimbatore: "CJB",
  dehradun: "DED",
  delhi: "DEL",
  "new delhi": "DEL",
  dibrugarh: "DIB",
  gaya: "GAY",
  goa: "GOI",
  guwahati: "GAU",
  gwalior: "GWL",
  hubli: "HBX",
  hyderabad: "HYD",
  imphal: "IMF",
  indore: "IDR",
  jaipur: "JAI",
  jammu: "IXJ",
  jodhpur: "JDH",
  kanpur: "KNU",
  kochi: "COK",
  kolkata: "CCU",
  kozhikode: "CCJ",
  calicut: "CCJ",
  leh: "IXL",
  lucknow: "LKO",
  madurai: "IXM",
  mangalore: "IXE",
  mangaluru: "IXE",
  mumbai: "BOM",
  mysore: "MYQ",
  mysuru: "MYQ",
  nagpur: "NAG",
  nashik: "ISK",
  patna: "PAT",
  pune: "PNQ",
  raipur: "RPR",
  rajkot: "RAJ",
  ranchi: "IXR",
  shillong: "SHL",
  srinagar: "SXR",
  surat: "STV",
  tirupati: "TIR",
  trivandrum: "TRV",
  thiruvananthapuram: "TRV",
  udaipur: "UDR",
  vadodara: "BDQ",
  varanasi: "VNS",
  vijayawada: "VGA",
  visakhapatnam: "VTZ",
  vizag: "VTZ",
};

export function toIata(city: string): string | null {
  return resolveAirport(city)?.code ?? null;
}

// IATA code -> city/municipality name, from list-of-airports-in-india.csv
// (+ the 4 post-2020 airports patched into district-hubs.ts). Used only to
// phrase the "nearest airport" caveat in resolveAirport() below.
export const AIRPORT_CITY: Record<string, string> = {
  AIP: "Adampur",
  AJL: "Aizawl",
  AMD: "Ahmedabad",
  ATQ: "Amritsar",
  BBI: "Bhubaneswar",
  BDQ: "Vadodara",
  BHJ: "Bhuj",
  BHO: "Bhopal",
  BHU: "Bhavnagar",
  BLR: "Bangalore",
  BOM: "Mumbai",
  CCJ: "Calicut",
  CCU: "Kolkata",
  CDP: "Kadapa",
  CJB: "Coimbatore",
  CNN: "Kannur",
  COK: "Kochi",
  DED: "Dehradun",
  DEL: "New Delhi",
  DIB: "Dibrugarh",
  DIU: "Diu",
  DMU: "Dimapur",
  GAU: "Guwahati",
  GBI: "Kalaburagi",
  GOI: "Vasco da Gama",
  GOP: "Gorakhpur",
  GWL: "Gwalior",
  HBX: "Hubli",
  HGI: "Itanagar",
  HJR: "Khajuraho",
  HYD: "Hyderabad",
  IDR: "Indore",
  IMF: "Imphal",
  ISK: "Nasik",
  IXA: "Agartala",
  IXB: "Siliguri",
  IXC: "Chandigarh",
  IXE: "Mangalore",
  IXG: "Belgaum",
  IXI: "Lilabari",
  IXJ: "Jammu",
  IXL: "Leh",
  IXM: "Madurai",
  IXP: "Pathankot",
  IXR: "Ranchi",
  IXS: "Silchar",
  IXU: "Aurangabad",
  IXY: "Kandla",
  IXZ: "Port Blair",
  JAI: "Jaipur",
  JDH: "Jodhpur",
  JGA: "Jamnagar",
  JRH: "Jorhat",
  KBK: "Kushinagar",
  KQH: "Kishangarh (Ajmer)",
  LKO: "Lucknow",
  LTU: "Latur",
  MAA: "Chennai",
  NAG: "Nagpur",
  NDC: "Nanded",
  PAT: "Patna",
  PBD: "Porbandar",
  PNQ: "Pune",
  RAJ: "Rajkot",
  RDP: "Durgapur",
  RJA: "Rajahmundry",
  RPR: "Raipur",
  SAG: "Shirdi",
  SDW: "Sindhudurg",
  SHL: "Shillong",
  SXR: "Srinagar",
  TCR: "Thoothukudi",
  TIR: "Tirupati",
  TRV: "Thiruvananthapuram",
  TRZ: "Tiruchirappally",
  UDR: "Udaipur",
  VNS: "Varanasi",
  VTZ: "Visakhapatnam",
};

export interface ResolvedAirport {
  code: string;
  /** set when `code` is a "nearest airport" proxy, not the searched place's own */
  viaCity?: string;
}

export function resolveAirport(city: string): ResolvedAirport | null {
  const key = city.trim().toLowerCase();
  if (IATA[key]) return { code: IATA[key] };
  const iata = DISTRICT_HUBS[key]?.iata;
  if (!iata) return null;
  const viaCity = AIRPORT_CITY[iata];
  return viaCity ? { code: iata, viaCity } : { code: iata };
}
